### ISSUE TITLE
Add loading times

### ISSUE THREAD

**Issue by C-Lodder** [ciar4n/themeglobe#13]
Possibly add the following loading times:

- First Contentful Paint
- First Meaningful Paint
- Speed Index
- First CPU Idle
- Time to Interactive
- Estimated Input Latency

Scores out of 100 are easy indicators but those more tech savy may want to know more details about loading times

@ciar4n ?

**Comment by ciar4n** [comment]
Nice idea. Of these are their any details more likely influenced by server set up rather than the template? Such details we can leave out?

**Comment by C-Lodder** [comment]
I supose you could leave out

- First CPU Idle
- Estimated Input Latency

**Comment by C-Lodder** [comment]
https://github.com/ciar4n/themeglobe/pull/16
