### ISSUE TITLE
Possible to add Joomlashack templates

### ISSUE THREAD

**Issue by stevejburge** [ciar4n/themeglobe#15]
Apologies if this is the wrong location to ask, but is it possible to add Joomlashack templates?
https://joomlashack.com/joomla-templates/

**Comment by ciar4n** [comment]
Sure. Leave it with me. Joomlashack was next on my list :)

**Comment by stevejburge** [comment]
awesome, thanks so much @ciar4n

**Comment by ciar4n** [comment]
Joomlashack templates have been added. Feel free to submit PRs for any changes/additions.
